DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS movie_detail;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  is_registered INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE `movie` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT UNIQUE NOT NULL,
	`description`	TEXT NOT NULL,
	`released_date` TEXT NOT NULL,
	`rating`    REAL NOT NULL
);


CREATE TABLE `movie_detail` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`movie_id`	INTEGER NOT NULL,
	`key`	TEXT NOT NULL,
	`value`	TEXT NOT NULL,
	FOREIGN KEY(`movie_id`) REFERENCES `movies`(`id`)
);
