BEGIN TRANSACTION;
INSERT INTO user VALUES(1,'test','pbkdf2:sha256:50000$TCI4GzcX$0de171a4f4dac32e3364c7ddc7c14f3e2fa61f2d17574483f7ffbb431b4acb2f',1);
INSERT INTO user VALUES(2,'other','pbkdf2:sha256:50000$TCI4GzcX$0de171a4f4dac32e3364c7ddc7c14f3e2fa61f2d17574483f7ffbb431b4acb2f',0);
INSERT INTO movie VALUES(1,'The Shawshank Redemption',' is a movie starring Tim Robbins, Morgan Freeman, and Bob Gunton. Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.','1994-09-23',9.3000000000000007105);
INSERT INTO movie VALUES(2,'The Godfather',' is a movie starring Marlon Brando, Al Pacino, and James Caan. The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.','1972-03-24',9.1999999999999992894);
INSERT INTO movie VALUES(3,'The Dark Knight',' is a movie starring Christian Bale, Heath Ledger, and Aaron Eckhart. When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and...','2008-07-16',9.0);
INSERT INTO movie VALUES(4,'The Godfather: Part II',' is a movie starring Al Pacino, Robert De Niro, and Robert Duvall. The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the...','1974-12-18',9.0);
INSERT INTO movie VALUES(5,'The Lord of the Rings: The Return of the King',' is a movie starring Elijah Wood, Viggo Mortensen, and Ian McKellen. Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach...','2003-12-17',8.9000000000000003552);
INSERT INTO movie VALUES(6,'Pulp Fiction',' is a movie starring John Travolta, Uma Thurman, and Samuel L. Jackson. The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.','1994-09-10',8.9000000000000003552);
INSERT INTO movie VALUES(7,'Schindler''s List',' is a movie starring Liam Neeson, Ralph Fiennes, and Ben Kingsley. In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing...','1993-12-15',8.9000000000000003552);
INSERT INTO movie VALUES(8,'12 Angry Men',' is a movie starring Henry Fonda, Lee J. Cobb, and Martin Balsam. A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.','1957-04-10',8.9000000000000003552);
INSERT INTO movie VALUES(9,'Inception',' is a movie starring Leonardo DiCaprio, Joseph Gordon-Levitt, and Ellen Page. A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a...','2010-07-14',8.8000000000000007105);
INSERT INTO movie VALUES(10,'Fight Club',' is a movie starring Brad Pitt, Edward Norton, and Meat Loaf. An insomniac office worker and a devil-may-care soapmaker form an underground  that evolves into something much, much more.','1999-10-15',8.8000000000000007105);
INSERT INTO movie VALUES(11,'The Lord of the Rings: The Fellowship of the Ring',' is a movie starring Elijah Wood, Ian McKellen, and Orlando Bloom. A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save...','2001-12-19',8.8000000000000007105);
INSERT INTO movie VALUES(12,'Forrest Gump',' is a movie starring Tom Hanks, Robin Wright, and Gary Sinise. The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with...','1994-07-06',8.8000000000000007105);
INSERT INTO movie VALUES(13,'Il buono, il brutto, il cattivo',' is a movie starring Clint Eastwood, Eli Wallach, and Lee Van Cleef. A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote...','1966-12-23',8.8000000000000007105);
INSERT INTO movie VALUES(14,'The Lord of the Rings: The Two Towers',' is a movie starring Elijah Wood, Ian McKellen, and Viggo Mortensen. While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against...','2002-12-18',8.6999999999999992894);
INSERT INTO movie VALUES(15,'The Matrix',' is a movie starring Keanu Reeves, Laurence Fishburne, and Carrie-Anne Moss. A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.','1999-03-31',8.6999999999999992894);
INSERT INTO movie VALUES(16,'Goodfellas',' is a movie starring Robert De Niro, Ray Liotta, and Joe Pesci. The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the...','1990-09-12',8.6999999999999992894);
INSERT INTO movie VALUES(17,'Star Wars: Episode V - The Empire Strikes Back',' is a movie starring Mark Hamill, Harrison Ford, and Carrie Fisher. After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training...','1980-05-21',8.6999999999999992894);
INSERT INTO movie VALUES(18,'One Flew Over the Cuckoo''s Nest',' is a movie starring Jack Nicholson, Louise Fletcher, and Will Sampson. A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up...','1975-11-19',8.6999999999999992894);
INSERT INTO movie VALUES(19,'Seppuku',' is a movie starring Tatsuya Nakadai, Akira Ishihama, and Shima Iwashita. When a ronin requesting  at a feudal lord''s palace is told of the brutal suicide of another ronin who previously visited, he reveals how their...','1962-09-16',8.6999999999999992894);
INSERT INTO movie VALUES(20,'Gisaengchung',' is a movie starring Kang-ho Song, Sun-kyun Lee, and Yeo-jeong Jo. A poor family, the Kims, con their way into becoming the servants of a rich family, the Parks. But their easy life gets complicated when their deception...','2019-05-30',8.5999999999999996447);
INSERT INTO movie VALUES(21,'Interstellar',' is a movie starring Matthew McConaughey, Anne Hathaway, and Jessica Chastain. A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.','2014-11-05',8.5999999999999996447);
INSERT INTO movie VALUES(22,'Cidade de Deus',' is a movie starring Alexandre Rodrigues, Leandro Firmino, and Matheus Nachtergaele. In the slums of Rio, two kids'' paths diverge as one struggles to become a photographer and the other a kingpin.','2002-08-30',8.5999999999999996447);
INSERT INTO movie VALUES(23,'Sen to Chihiro no kamikakushi',' is a movie starring Daveigh Chase, Suzanne Pleshette, and Miyu Irino. During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and...','2001-07-20',8.5999999999999996447);
INSERT INTO movie VALUES(24,'Saving Private Ryan',' is a movie starring Tom Hanks, Matt Damon, and Tom Sizemore. Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.','1998-07-24',8.5999999999999996447);
INSERT INTO movie VALUES(25,'The Green Mile',' is a movie starring Tom Hanks, Michael Clarke Duncan, and David Morse. The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.','1999-12-10',8.5999999999999996447);
INSERT INTO movie_detail VALUES(1,1,'actor','William Sadler');
INSERT INTO movie_detail VALUES(2,1,'actor','Morgan Freeman');
INSERT INTO movie_detail VALUES(3,1,'actor','Tim Robbins');
INSERT INTO movie_detail VALUES(4,1,'actor','Bob Gunton');
INSERT INTO movie_detail VALUES(5,1,'creator','Stephen King');
INSERT INTO movie_detail VALUES(6,1,'creator','Frank Darabont');
INSERT INTO movie_detail VALUES(7,1,'director','Frank Darabont');
INSERT INTO movie_detail VALUES(8,1,'genre','Drama');
INSERT INTO movie_detail VALUES(9,2,'actor','Diane Keaton');
INSERT INTO movie_detail VALUES(10,2,'actor','Al Pacino');
INSERT INTO movie_detail VALUES(11,2,'actor','Marlon Brando');
INSERT INTO movie_detail VALUES(12,2,'actor','James Caan');
INSERT INTO movie_detail VALUES(13,2,'creator','Francis Ford Coppola');
INSERT INTO movie_detail VALUES(14,2,'creator','Mario Puzo');
INSERT INTO movie_detail VALUES(15,2,'director','Francis Ford Coppola');
INSERT INTO movie_detail VALUES(16,2,'genre','Drama');
INSERT INTO movie_detail VALUES(17,2,'genre','Crime');
INSERT INTO movie_detail VALUES(18,3,'actor','Aaron Eckhart');
INSERT INTO movie_detail VALUES(19,3,'actor','Michael Caine');
INSERT INTO movie_detail VALUES(20,3,'actor','Heath Ledger');
INSERT INTO movie_detail VALUES(21,3,'actor','Christian Bale');
INSERT INTO movie_detail VALUES(22,3,'creator','Bob Kane');
INSERT INTO movie_detail VALUES(23,3,'creator','Jonathan Nolan');
INSERT INTO movie_detail VALUES(24,3,'creator','Christopher Nolan');
INSERT INTO movie_detail VALUES(25,3,'creator','David S. Goyer');
INSERT INTO movie_detail VALUES(26,3,'director','Christopher Nolan');
INSERT INTO movie_detail VALUES(27,3,'genre','Drama');
INSERT INTO movie_detail VALUES(28,3,'genre','Action');
INSERT INTO movie_detail VALUES(29,3,'genre','Crime');
INSERT INTO movie_detail VALUES(30,3,'genre','Thriller');
INSERT INTO movie_detail VALUES(31,4,'actor','Robert De Niro');
INSERT INTO movie_detail VALUES(32,4,'actor','Diane Keaton');
INSERT INTO movie_detail VALUES(33,4,'actor','Al Pacino');
INSERT INTO movie_detail VALUES(34,4,'actor','Robert Duvall');
INSERT INTO movie_detail VALUES(35,4,'creator','Francis Ford Coppola');
INSERT INTO movie_detail VALUES(36,4,'creator','Mario Puzo');
INSERT INTO movie_detail VALUES(37,4,'director','Francis Ford Coppola');
INSERT INTO movie_detail VALUES(38,4,'genre','Drama');
INSERT INTO movie_detail VALUES(39,4,'genre','Crime');
INSERT INTO movie_detail VALUES(40,5,'actor','Viggo Mortensen');
INSERT INTO movie_detail VALUES(41,5,'actor','Orlando Bloom');
INSERT INTO movie_detail VALUES(42,5,'actor','Elijah Wood');
INSERT INTO movie_detail VALUES(43,5,'actor','Ian McKellen');
INSERT INTO movie_detail VALUES(44,5,'creator','Fran Walsh');
INSERT INTO movie_detail VALUES(45,5,'creator','J.R.R. Tolkien');
INSERT INTO movie_detail VALUES(46,5,'creator','Peter Jackson');
INSERT INTO movie_detail VALUES(47,5,'creator','Philippa Boyens');
INSERT INTO movie_detail VALUES(48,5,'director','Peter Jackson');
INSERT INTO movie_detail VALUES(49,5,'genre','Adventure');
INSERT INTO movie_detail VALUES(50,5,'genre','Drama');
INSERT INTO movie_detail VALUES(51,5,'genre','Fantasy');
INSERT INTO movie_detail VALUES(52,6,'actor','John Travolta');
INSERT INTO movie_detail VALUES(53,6,'actor','Samuel L. Jackson');
INSERT INTO movie_detail VALUES(54,6,'actor','Uma Thurman');
INSERT INTO movie_detail VALUES(55,6,'actor','Bruce Willis');
INSERT INTO movie_detail VALUES(56,6,'creator','Quentin Tarantino');
INSERT INTO movie_detail VALUES(57,6,'creator','Roger Avary');
INSERT INTO movie_detail VALUES(58,6,'director','Quentin Tarantino');
INSERT INTO movie_detail VALUES(59,6,'genre','Drama');
INSERT INTO movie_detail VALUES(60,6,'genre','Crime');
INSERT INTO movie_detail VALUES(61,7,'actor','Ralph Fiennes');
INSERT INTO movie_detail VALUES(62,7,'actor','Ben Kingsley');
INSERT INTO movie_detail VALUES(63,7,'actor','Caroline Goodall');
INSERT INTO movie_detail VALUES(64,7,'actor','Liam Neeson');
INSERT INTO movie_detail VALUES(65,7,'creator','Thomas Keneally');
INSERT INTO movie_detail VALUES(66,7,'creator','Steven Zaillian');
INSERT INTO movie_detail VALUES(67,7,'director','Steven Spielberg');
INSERT INTO movie_detail VALUES(68,7,'genre','Drama');
INSERT INTO movie_detail VALUES(69,7,'genre','Biography');
INSERT INTO movie_detail VALUES(70,7,'genre','History');
INSERT INTO movie_detail VALUES(71,8,'actor','Martin Balsam');
INSERT INTO movie_detail VALUES(72,8,'actor','Henry Fonda');
INSERT INTO movie_detail VALUES(73,8,'actor','John Fiedler');
INSERT INTO movie_detail VALUES(74,8,'actor','Lee J. Cobb');
INSERT INTO movie_detail VALUES(75,8,'creator','Reginald Rose');
INSERT INTO movie_detail VALUES(76,8,'director','Sidney Lumet');
INSERT INTO movie_detail VALUES(77,8,'genre','Drama');
INSERT INTO movie_detail VALUES(78,9,'actor','Leonardo DiCaprio');
INSERT INTO movie_detail VALUES(79,9,'actor','Joseph Gordon-Levitt');
INSERT INTO movie_detail VALUES(80,9,'actor','Ken Watanabe');
INSERT INTO movie_detail VALUES(81,9,'actor','Ellen Page');
INSERT INTO movie_detail VALUES(82,9,'creator','Christopher Nolan');
INSERT INTO movie_detail VALUES(83,9,'director','Christopher Nolan');
INSERT INTO movie_detail VALUES(84,9,'genre','Adventure');
INSERT INTO movie_detail VALUES(85,9,'genre','Action');
INSERT INTO movie_detail VALUES(86,9,'genre','Thriller');
INSERT INTO movie_detail VALUES(87,9,'genre','Sci-Fi');
INSERT INTO movie_detail VALUES(88,10,'actor','Edward Norton');
INSERT INTO movie_detail VALUES(89,10,'actor','Meat Loaf');
INSERT INTO movie_detail VALUES(90,10,'actor','Brad Pitt');
INSERT INTO movie_detail VALUES(91,10,'actor','Zach Grenier');
INSERT INTO movie_detail VALUES(92,10,'creator','Jim Uhls');
INSERT INTO movie_detail VALUES(93,10,'creator','Chuck Palahniuk');
INSERT INTO movie_detail VALUES(94,10,'director','David Fincher');
INSERT INTO movie_detail VALUES(95,10,'genre','Drama');
INSERT INTO movie_detail VALUES(96,11,'actor','Sean Bean');
INSERT INTO movie_detail VALUES(97,11,'actor','Orlando Bloom');
INSERT INTO movie_detail VALUES(98,11,'actor','Elijah Wood');
INSERT INTO movie_detail VALUES(99,11,'actor','Ian McKellen');
INSERT INTO movie_detail VALUES(100,11,'creator','Fran Walsh');
INSERT INTO movie_detail VALUES(101,11,'creator','J.R.R. Tolkien');
INSERT INTO movie_detail VALUES(102,11,'creator','Peter Jackson');
INSERT INTO movie_detail VALUES(103,11,'creator','Philippa Boyens');
INSERT INTO movie_detail VALUES(104,11,'director','Peter Jackson');
INSERT INTO movie_detail VALUES(105,11,'genre','Adventure');
INSERT INTO movie_detail VALUES(106,11,'genre','Drama');
INSERT INTO movie_detail VALUES(107,11,'genre','Action');
INSERT INTO movie_detail VALUES(108,11,'genre','Fantasy');
INSERT INTO movie_detail VALUES(109,12,'actor','Robin Wright');
INSERT INTO movie_detail VALUES(110,12,'actor','Tom Hanks');
INSERT INTO movie_detail VALUES(111,12,'actor','Sally Field');
INSERT INTO movie_detail VALUES(112,12,'actor','Gary Sinise');
INSERT INTO movie_detail VALUES(113,12,'creator','Winston Groom');
INSERT INTO movie_detail VALUES(114,12,'creator','Eric Roth');
INSERT INTO movie_detail VALUES(115,12,'director','Robert Zemeckis');
INSERT INTO movie_detail VALUES(116,12,'genre','Drama');
INSERT INTO movie_detail VALUES(117,12,'genre','Romance');
INSERT INTO movie_detail VALUES(118,13,'actor','Eli Wallach');
INSERT INTO movie_detail VALUES(119,13,'actor','Aldo Giuffrè');
INSERT INTO movie_detail VALUES(120,13,'actor','Clint Eastwood');
INSERT INTO movie_detail VALUES(121,13,'actor','Lee Van Cleef');
INSERT INTO movie_detail VALUES(122,13,'creator','Sergio Leone');
INSERT INTO movie_detail VALUES(123,13,'creator','Agenore Incrocci');
INSERT INTO movie_detail VALUES(124,13,'creator','Luciano Vincenzoni');
INSERT INTO movie_detail VALUES(125,13,'creator','Furio Scarpelli');
INSERT INTO movie_detail VALUES(126,13,'director','Sergio Leone');
INSERT INTO movie_detail VALUES(127,13,'genre','Western');
INSERT INTO movie_detail VALUES(128,14,'actor','Viggo Mortensen');
INSERT INTO movie_detail VALUES(129,14,'actor','Orlando Bloom');
INSERT INTO movie_detail VALUES(130,14,'actor','Elijah Wood');
INSERT INTO movie_detail VALUES(131,14,'actor','Ian McKellen');
INSERT INTO movie_detail VALUES(132,14,'creator','Fran Walsh');
INSERT INTO movie_detail VALUES(133,14,'creator','Stephen Sinclair');
INSERT INTO movie_detail VALUES(134,14,'creator','J.R.R. Tolkien');
INSERT INTO movie_detail VALUES(135,14,'creator','Peter Jackson');
INSERT INTO movie_detail VALUES(136,14,'creator','Philippa Boyens');
INSERT INTO movie_detail VALUES(137,14,'director','Peter Jackson');
INSERT INTO movie_detail VALUES(138,14,'genre','Adventure');
INSERT INTO movie_detail VALUES(139,14,'genre','Drama');
INSERT INTO movie_detail VALUES(140,14,'genre','Fantasy');
INSERT INTO movie_detail VALUES(141,15,'actor','Laurence Fishburne');
INSERT INTO movie_detail VALUES(142,15,'actor','Keanu Reeves');
INSERT INTO movie_detail VALUES(143,15,'actor','Carrie-Anne Moss');
INSERT INTO movie_detail VALUES(144,15,'actor','Hugo Weaving');
INSERT INTO movie_detail VALUES(145,15,'creator','Lilly Wachowski');
INSERT INTO movie_detail VALUES(146,15,'creator','Lana Wachowski');
INSERT INTO movie_detail VALUES(147,15,'director','Lilly Wachowski');
INSERT INTO movie_detail VALUES(148,15,'director','Lana Wachowski');
INSERT INTO movie_detail VALUES(149,15,'genre','Action');
INSERT INTO movie_detail VALUES(150,15,'genre','Sci-Fi');
INSERT INTO movie_detail VALUES(151,16,'actor','Robert De Niro');
INSERT INTO movie_detail VALUES(152,16,'actor','Ray Liotta');
INSERT INTO movie_detail VALUES(153,16,'actor','Lorraine Bracco');
INSERT INTO movie_detail VALUES(154,16,'actor','Joe Pesci');
INSERT INTO movie_detail VALUES(155,16,'creator','Martin Scorsese');
INSERT INTO movie_detail VALUES(156,16,'creator','Nicholas Pileggi');
INSERT INTO movie_detail VALUES(157,16,'director','Martin Scorsese');
INSERT INTO movie_detail VALUES(158,16,'genre','Drama');
INSERT INTO movie_detail VALUES(159,16,'genre','Crime');
INSERT INTO movie_detail VALUES(160,16,'genre','Biography');
INSERT INTO movie_detail VALUES(161,17,'actor','Mark Hamill');
INSERT INTO movie_detail VALUES(162,17,'actor','Carrie Fisher');
INSERT INTO movie_detail VALUES(163,17,'actor','Harrison Ford');
INSERT INTO movie_detail VALUES(164,17,'actor','Billy Dee Williams');
INSERT INTO movie_detail VALUES(165,17,'creator','Lawrence Kasdan');
INSERT INTO movie_detail VALUES(166,17,'creator','George Lucas');
INSERT INTO movie_detail VALUES(167,17,'creator','Leigh Brackett');
INSERT INTO movie_detail VALUES(168,17,'director','Irvin Kershner');
INSERT INTO movie_detail VALUES(169,17,'genre','Adventure');
INSERT INTO movie_detail VALUES(170,17,'genre','Action');
INSERT INTO movie_detail VALUES(171,17,'genre','Sci-Fi');
INSERT INTO movie_detail VALUES(172,17,'genre','Fantasy');
INSERT INTO movie_detail VALUES(173,18,'actor','Louise Fletcher');
INSERT INTO movie_detail VALUES(174,18,'actor','Michael Berryman');
INSERT INTO movie_detail VALUES(175,18,'actor','Will Sampson');
INSERT INTO movie_detail VALUES(176,18,'actor','Jack Nicholson');
INSERT INTO movie_detail VALUES(177,18,'creator','Bo Goldman');
INSERT INTO movie_detail VALUES(178,18,'creator','Dale Wasserman');
INSERT INTO movie_detail VALUES(179,18,'creator','Ken Kesey');
INSERT INTO movie_detail VALUES(180,18,'creator','Lawrence Hauben');
INSERT INTO movie_detail VALUES(181,18,'director','Milos Forman');
INSERT INTO movie_detail VALUES(182,18,'genre','Drama');
INSERT INTO movie_detail VALUES(183,19,'actor','Tatsuya Nakadai');
INSERT INTO movie_detail VALUES(184,19,'actor','Akira Ishihama');
INSERT INTO movie_detail VALUES(185,19,'actor','Shima Iwashita');
INSERT INTO movie_detail VALUES(186,19,'actor','Tetsurô Tanba');
INSERT INTO movie_detail VALUES(187,19,'creator','Yasuhiko Takiguchi');
INSERT INTO movie_detail VALUES(188,19,'creator','Shinobu Hashimoto');
INSERT INTO movie_detail VALUES(189,19,'director','Masaki Kobayashi');
INSERT INTO movie_detail VALUES(190,19,'genre','Drama');
INSERT INTO movie_detail VALUES(191,19,'genre','Action');
INSERT INTO movie_detail VALUES(192,19,'genre','History');
INSERT INTO movie_detail VALUES(193,20,'actor','Yeo-jeong Jo');
INSERT INTO movie_detail VALUES(194,20,'actor','Woo-sik Choi');
INSERT INTO movie_detail VALUES(195,20,'actor','Kang-ho Song');
INSERT INTO movie_detail VALUES(196,20,'actor','Sun-kyun Lee');
INSERT INTO movie_detail VALUES(197,20,'creator','Jin Won Han');
INSERT INTO movie_detail VALUES(198,20,'creator','Bong Joon Ho');
INSERT INTO movie_detail VALUES(199,20,'director','Bong Joon Ho');
INSERT INTO movie_detail VALUES(200,20,'genre','Drama');
INSERT INTO movie_detail VALUES(201,20,'genre','Thriller');
INSERT INTO movie_detail VALUES(202,20,'genre','Comedy');
INSERT INTO movie_detail VALUES(203,21,'actor','Anne Hathaway');
INSERT INTO movie_detail VALUES(204,21,'actor','Matthew McConaughey');
INSERT INTO movie_detail VALUES(205,21,'actor','Jessica Chastain');
INSERT INTO movie_detail VALUES(206,21,'actor','Mackenzie Foy');
INSERT INTO movie_detail VALUES(207,21,'creator','Jonathan Nolan');
INSERT INTO movie_detail VALUES(208,21,'creator','Christopher Nolan');
INSERT INTO movie_detail VALUES(209,21,'director','Christopher Nolan');
INSERT INTO movie_detail VALUES(210,21,'genre','Adventure');
INSERT INTO movie_detail VALUES(211,21,'genre','Drama');
INSERT INTO movie_detail VALUES(212,21,'genre','Thriller');
INSERT INTO movie_detail VALUES(213,21,'genre','Sci-Fi');
INSERT INTO movie_detail VALUES(214,22,'actor','Phellipe Haagensen');
INSERT INTO movie_detail VALUES(215,22,'actor','Leandro Firmino');
INSERT INTO movie_detail VALUES(216,22,'actor','Matheus Nachtergaele');
INSERT INTO movie_detail VALUES(217,22,'actor','Alexandre Rodrigues');
INSERT INTO movie_detail VALUES(218,22,'creator','Bráulio Mantovani');
INSERT INTO movie_detail VALUES(219,22,'creator','Paulo Lins');
INSERT INTO movie_detail VALUES(220,22,'director','Kátia Lund');
INSERT INTO movie_detail VALUES(221,22,'director','Fernando Meirelles');
INSERT INTO movie_detail VALUES(222,22,'genre','Drama');
INSERT INTO movie_detail VALUES(223,22,'genre','Crime');
INSERT INTO movie_detail VALUES(224,23,'actor','Daveigh Chase');
INSERT INTO movie_detail VALUES(225,23,'actor','Rumi Hiiragi');
INSERT INTO movie_detail VALUES(226,23,'actor','Miyu Irino');
INSERT INTO movie_detail VALUES(227,23,'actor','Suzanne Pleshette');
INSERT INTO movie_detail VALUES(228,23,'creator','Hayao Miyazaki');
INSERT INTO movie_detail VALUES(229,23,'director','Hayao Miyazaki');
INSERT INTO movie_detail VALUES(230,23,'genre','Adventure');
INSERT INTO movie_detail VALUES(231,23,'genre','Mystery');
INSERT INTO movie_detail VALUES(232,23,'genre','Animation');
INSERT INTO movie_detail VALUES(233,23,'genre','Fantasy');
INSERT INTO movie_detail VALUES(234,23,'genre','Family');
INSERT INTO movie_detail VALUES(235,24,'actor','Edward Burns');
INSERT INTO movie_detail VALUES(236,24,'actor','Tom Sizemore');
INSERT INTO movie_detail VALUES(237,24,'actor','Matt Damon');
INSERT INTO movie_detail VALUES(238,24,'actor','Tom Hanks');
INSERT INTO movie_detail VALUES(239,24,'creator','Robert Rodat');
INSERT INTO movie_detail VALUES(240,24,'director','Steven Spielberg');
INSERT INTO movie_detail VALUES(241,24,'genre','Drama');
INSERT INTO movie_detail VALUES(242,24,'genre','War');
INSERT INTO movie_detail VALUES(243,25,'actor','David Morse');
INSERT INTO movie_detail VALUES(244,25,'actor','Michael Clarke Duncan');
INSERT INTO movie_detail VALUES(245,25,'actor','Bonnie Hunt');
INSERT INTO movie_detail VALUES(246,25,'actor','Tom Hanks');
INSERT INTO movie_detail VALUES(247,25,'creator','Stephen King');
INSERT INTO movie_detail VALUES(248,25,'creator','Frank Darabont');
INSERT INTO movie_detail VALUES(249,25,'director','Frank Darabont');
INSERT INTO movie_detail VALUES(250,25,'genre','Drama');
INSERT INTO movie_detail VALUES(251,25,'genre','Crime');
INSERT INTO movie_detail VALUES(252,25,'genre','Mystery');
INSERT INTO movie_detail VALUES(253,25,'genre','Fantasy');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('user',2);
INSERT INTO sqlite_sequence VALUES('movie',25);
INSERT INTO sqlite_sequence VALUES('movie_detail',253);
COMMIT;
